//! Core types for workflow tracing (Task 232).
//!
//! Records the lifecycle of LLM-driven code generation + local validation loops.

use serde::{Deserialize, Serialize};

/// A single step in a code-generation + validation workflow.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum WorkflowStep {
    /// The original user prompt that started the workflow.
    UserPrompt(String),

    /// Code generated by the LLM (before any validation).
    LlmGeneratedCode(String),

    /// Execution of a local validation tool.
    ToolRun {
        /// Name of the tool, e.g. "cargo check", "cargo clippy", "cargo test".
        tool: String,
        /// Captured stdout/stderr (truncated if very long).
        output: String,
        /// Whether the tool exited successfully.
        success: bool,
    },

    /// Decision after running validation tools.
    Decision {
        /// true = all checks passed, false = at least one failed.
        passed: bool,
    },

    /// The trace is being sent back to the LLM for an automatic fix attempt.
    ReturnedToLlm(String),

    /// The trace is being returned to the user / editor (final result).
    ReturnedToUser(String),
}

/// Records the full sequence of steps for one workflow run.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct WorkflowTrace {
    pub steps: Vec<WorkflowStep>,
}

impl WorkflowTrace {
    /// Create a new empty trace.
    pub fn new() -> Self {
        Self::default()
    }

    /// Append a step.
    pub fn push(&mut self, step: WorkflowStep) {
        self.steps.push(step);
    }

    /// Pretty-print the trace to stdout (matches the style requested in task 232).
    pub fn print(&self) {
        println!("\n=== Workflow Trace ===");
        for (i, step) in self.steps.iter().enumerate() {
            match step {
                WorkflowStep::UserPrompt(p) => {
                    println!("{i:02}: UserPrompt: {}", truncate(p, 80));
                }
                WorkflowStep::LlmGeneratedCode(code) => {
                    println!("{i:02}: LlmGeneratedCode ({} bytes)", code.len());
                }
                WorkflowStep::ToolRun { tool, output, success } => {
                    let status = if *success { "✓" } else { "✗" };
                    println!(
                        "{i:02}: ToolRun {} {}  ({} bytes output)",
                        status,
                        tool,
                        output.len()
                    );
                }
                WorkflowStep::Decision { passed } => {
                    let status = if *passed { "PASS" } else { "FAIL" };
                    println!("{i:02}: Decision: {}", status);
                }
                WorkflowStep::ReturnedToLlm(reason) => {
                    println!("{i:02}: ReturnedToLlm: {}", truncate(reason, 60));
                }
                WorkflowStep::ReturnedToUser(msg) => {
                    println!("{i:02}: ReturnedToUser: {}", truncate(msg, 60));
                }
            }
        }
        println!("======================\n");
    }

    /// Returns true if the last decision (if any) was a pass.
    pub fn last_decision_passed(&self) -> Option<bool> {
        self.steps.iter().rev().find_map(|s| {
            if let WorkflowStep::Decision { passed } = s {
                Some(*passed)
            } else {
                None
            }
        })
    }
}

fn truncate(s: &str, max: usize) -> String {
    if s.len() <= max {
        s.to_string()
    } else {
        format!("{}…", &s[..max])
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn basic_workflow_trace_roundtrip() {
        let mut trace = WorkflowTrace::new();

        trace.push(WorkflowStep::UserPrompt("fix the bug".into()));
        trace.push(WorkflowStep::LlmGeneratedCode("fn main() {}".into()));
        trace.push(WorkflowStep::ToolRun {
            tool: "cargo check".into(),
            output: "error[E...".into(),
            success: false,
        });
        trace.push(WorkflowStep::Decision { passed: false });
        trace.push(WorkflowStep::ReturnedToLlm("please fix the error".into()));

        assert_eq!(trace.steps.len(), 5);
        assert_eq!(trace.last_decision_passed(), Some(false));

        // Should be serializable (for future JSON persistence)
        let json = serde_json::to_string(&trace).unwrap();
        let restored: WorkflowTrace = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.steps.len(), 5);
    }

    #[test]
    fn print_does_not_panic() {
        let mut trace = WorkflowTrace::new();
        trace.push(WorkflowStep::UserPrompt("hello".into()));
        trace.push(WorkflowStep::Decision { passed: true });
        trace.print(); // should just print, no crash
    }
}