//! HOH Autonomous Test Generation (Task 361.19)

use crate::hoh::state::PatchSet;
use serde::{Deserialize, Serialize};
use std::time::{SystemTime, UNIX_EPOCH};

fn now() -> u64 { SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs() }

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TestKind { Unit, Integration, PropertyBased, Regression }

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedTest {
    pub id: String,
    pub target_file: String,
    pub target_function: String,
    pub kind: TestKind,
    pub test_code: String,
    pub rationale: String,
}

pub struct TestGenerator { pub simulation_mode: bool }

impl TestGenerator {
    pub fn new(sim: bool) -> Self { Self { simulation_mode: sim } }

    /// Scan source file and generate test stubs for uncovered public functions.
    pub fn generate_for_file(&self, file_path: &str, content: &str, iteration_id: u64) -> Vec<GeneratedTest> {
        let mut tests = Vec::new();

        for (line_no, line) in content.lines().enumerate() {
            if !line.contains("pub fn ") { continue; }
            let fn_name = line.split("pub fn ").nth(1)
                .and_then(|s| s.split('(').next())
                .unwrap_or("unknown").to_string();
            if fn_name.starts_with("test_") || fn_name.contains("__") { continue; }

            // Check if a test already exists for this function
            let test_exists = content.contains(&format!("fn test_{}", fn_name));
            if test_exists { continue; }

            let test_code = if line.contains("async") {
                format!(
                    "#[tokio::test]\nasync fn test_{fn_name}() {{\n    // TODO: test {fn_name} at {file_path}:{line_no}\n    // Generated by HOH autonomous test generator\n}}"
                )
            } else {
                format!(
                    "#[test]\nfn test_{fn_name}() {{\n    // TODO: test {fn_name} at {file_path}:{line_no}\n    // Generated by HOH autonomous test generator\n}}"
                )
            };

            tests.push(GeneratedTest {
                id: format!("test-{}-{}-{}", iteration_id, file_path.len(), tests.len()),
                target_file: file_path.to_string(),
                target_function: fn_name.clone(),
                kind: if line.contains("async") { TestKind::Integration } else { TestKind::Unit },
                test_code,
                rationale: format!("No test found for public function '{}'", fn_name),
            });

            if tests.len() >= 5 { break; } // cap per file
        }
        tests
    }

    /// Scan the project and generate tests for un-covered public functions.
    pub fn generate_for_project(&self, project_root: &std::path::Path, iteration_id: u64) -> Vec<GeneratedTest> {
        let src = project_root.join("src");
        let mut all_tests = Vec::new();

        for entry in walkdir::WalkDir::new(&src).into_iter().flatten() {
            if entry.path().extension().and_then(|e| e.to_str()) != Some("rs") { continue; }
            let Ok(content) = std::fs::read_to_string(entry.path()) else { continue };
            let path = entry.path().to_string_lossy().to_string();
            let generated = self.generate_for_file(&path, &content, iteration_id);
            all_tests.extend(generated);
            if all_tests.len() >= 20 { break; }
        }
        all_tests
    }

    /// Convert generated tests into patch sets.
    pub fn to_patches(&self, tests: &[GeneratedTest], iteration_id: u64) -> Vec<PatchSet> {
        tests.iter().map(|t| PatchSet {
            id: format!("testgen-{}", t.id),
            files_changed: vec![t.target_file.clone()],
            diff_summary: format!("Generated test for {}::{}", t.target_file, t.target_function),
            source: "test_generation".to_string(),
            timestamp: now() + iteration_id,
            intended_content: Some(t.test_code.clone()),
        }).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generates_test_for_uncovered_fn() {
        let tgen = TestGenerator::new(true);
        let code = "pub fn compute_hash(input: &str) -> u64 { todo!() }";
        let tests = tgen.generate_for_file("src/utils.rs", code, 1);
        assert!(!tests.is_empty());
        assert!(tests[0].test_code.contains("compute_hash"));
    }

    #[test]
    fn test_skips_existing_tests() {
        let tgen = TestGenerator::new(true);
        let code = "pub fn foo() {}\n#[test]\nfn test_foo() {}\n";
        let tests = tgen.generate_for_file("src/lib.rs", code, 1);
        assert!(tests.is_empty() || tests.iter().all(|t| t.target_function != "foo"));
    }
}
